name: Build & Push Operator Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'  # Match go.mod

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate version tag
        id: version
        run: |
          TAG=$(git describe --tags --exact-match 2>/dev/null || echo "latest")
          SHA=$(git rev-parse --short HEAD)
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Build image using Makefile
        env:
          TAG: ghcr.io/${{ github.repository }}:${{ steps.version.outputs.tag }}
          LATEST: ghcr.io/${{ github.repository }}:latest
          SHA_TAG: ghcr.io/${{ github.repository }}:sha-${{ steps.version.outputs.sha }}
        run: |
          make docker TAG=$TAG
          docker tag $TAG $LATEST
          docker tag $TAG $SHA_TAG

      - name: Push all tags
        run: |
          docker push ghcr.io/${{ github.repository }} --all-tags