# .github/workflows/sync-and-build.yml
name: Sync Tags & Build

on:
  schedule:
    - cron: '0 4 * * *'  # Daily
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add upstream
        run: |
          git remote add upstream https://github.com/minio/operator.git || true
          git fetch upstream --tags

      - name: Push new tags
        run: git push origin --tags --force

      - name: Build latest
        uses: ./.github/workflows/docker-build.yml  # Reuse your existing build