# .github/workflows/sync-tags.yml
name: Sync Tags from Upstream

on:
  schedule:
    - cron: '0 3 * * *'  # Daily at 3 AM UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add upstream
        run: |
          git remote add upstream https://github.com/minio/operator.git || true
          git fetch upstream --tags

      - name: Push new tags
        run: |
          git push origin --tags --force